Fixes to check-sycl
* Consistently declare `class graph_impl` due to issue
```
In file included from /home/ewan/Development/dpc++/build_release/bin/../include/sycl/queue.hpp:21:
/home/ewan/Development/dpc++/build_release/bin/../include/sycl/handler.hpp:84:1: error: class 'graph_impl' was previously declared as a struct; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Werror,-Wmismatched-tags]
class graph_impl;
^
/home/ewan/Development/dpc++/build_release/bin/../include/sycl/ext/oneapi/experimental/graph.hpp:29:8: note: previous use is here
struct graph_impl;
```

* Use updated constructor in Mock testing
* Declare `mock_*` functions which lead to compilation failures when
  missing
* Forward declare `sycl::device` in graph.hpp header, otherwise there
  are issues if we include it before <sycl/sycl.hpp>